// Lead magnets — gated downloads. Add new ones here + a matching PDF in public/downloads/.
export type LeadMagnet = {
  slug: string;         // /resources/{slug}
  file: string;         // /downloads/{file}.pdf
  eyebrow: string;
  h1: string;
  keyword: string;
  title: string;        // <title>
  desc: string;         // meta description
  intro: string;
  bullets: string[];    // "what's inside"
  audience: string;
  industry?: string;    // HubSpot Industry value for segmentation (ICP guides)
  cover?: string;       // /images/guides/{slug}.jpg — cover preview image
};

export const MAGNETS: LeadMagnet[] = [
  {
    slug: "capability-statement",
    file: "/downloads/easy-rx-cycle-capability-statement.pdf",
    eyebrow: "Free download · for procurement & GPOs",
    h1: "Easy Rx Cycle Capability Statement",
    keyword: "medical waste capability statement",
    title: "Capability Statement — Easy Rx Cycle (Download)",
    desc: "Download the Easy Rx Cycle capability statement — DEA/EPA/DOT credentials, every regulated waste stream, nationwide coverage, and company data for your procurement team or GPO.",
    intro: "A one-page overview built for procurement teams, GPOs, and compliance officers — everything they need to vet and onboard Easy Rx Cycle as a vendor.",
    bullets: [
      "Company overview, legal entity, and company data (NAICS, coverage, contacts)",
      "Core competencies across all eight regulated waste streams",
      "Credentials: DEA-registered, EPA/RCRA, DOT/PHMSA, HIPAA & BAA",
      "What makes us different — one vendor, Certificate of Destruction, no contract",
    ],
    audience: "Procurement, GPOs, and compliance officers vetting a disposal vendor.",
    cover: "/images/guides/capability-statement.jpg",
  },
  {
    slug: "medical-waste-compliance-checklist",
    file: "/downloads/medical-waste-compliance-checklist.pdf",
    eyebrow: "Free download · stay audit-ready",
    h1: "Medical Waste Compliance Checklist",
    keyword: "medical waste compliance checklist",
    title: "Medical Waste Compliance Checklist (Free Download)",
    desc: "Download a practical, by-stream medical waste compliance checklist — sharps, biohazard, pharmaceutical, controlled substances, RCRA-hazardous, and trace chemo — to keep your healthcare facility audit-ready.",
    intro: "A practical, by-stream checklist to keep your healthcare facility audit-ready — covering every regulated waste stream, plus training and documentation.",
    bullets: [
      "Stream-by-stream checks: sharps, biohazard, pharmaceutical, controlled, RCRA, trace chemo",
      "Controlled-substance essentials: non-retrievable destruction, Form 41, Certificate of Destruction",
      "Training & documentation your inspectors look for",
      "Where one vendor can cover every stream you generate",
    ],
    audience: "Practice managers, compliance officers, and anyone responsible for waste at a healthcare facility.",
    cover: "/images/guides/medical-waste-compliance-checklist.jpg",
  },
  {
    slug: "dental-waste-disposal-guide",
    file: "/downloads/guides/dental-practices.pdf",
    eyebrow: "Free guide · for dental practices",
    h1: "The Dental Practice's Guide to Compliant Waste Disposal",
    keyword: "dental waste disposal guide",
    title: "Dental Waste Disposal Guide (Free Download)",
    desc: "Free dental waste disposal guide — every regulated stream a dental practice generates (sharps, amalgam, pharmaceuticals, controlled substances, biohazard, hazardous), the rule behind each, and how to dispose of it compliantly. No contract.",
    intro: "A plain-English reference to every regulated waste stream your dental practice generates — sharps, amalgam, pharmaceuticals, controlled substances, biohazard, and hazardous waste — and how to handle each one right.",
    bullets: [
      "Deep-dive on all 6 dental streams — what goes in, what doesn't, and why",
      "The rule behind each: OSHA, the EPA dental amalgam rule, DEA & RCRA",
      "A dental compliance checklist + the common mistakes that fail inspections",
      "A 'which kit for which stream' quick reference + a 7-question dental FAQ",
    ],
    audience: "Dentists, office managers, and compliance leads at dental practices and DSOs.",
    industry: "Dental",
    cover: "/images/guides/dental-practices.jpg",
  },
  {
    slug: "veterinary-waste-disposal-guide",
    file: "/downloads/guides/veterinary-practices.pdf",
    eyebrow: "Free guide · for veterinary practices",
    h1: "The Veterinary Practice's Guide to Compliant Waste Disposal",
    keyword: "veterinary waste disposal guide",
    title: "Veterinary Waste Disposal Guide (Free Download)",
    desc: "Free veterinary waste disposal guide — controlled drugs (ketamine, euthanasia solution), sharps, expired meds, and biohazard: every regulated stream a veterinary practice generates, the rules, and how to dispose of each compliantly.",
    intro: "A plain-English reference to every regulated waste stream your veterinary practice generates — controlled substances (ketamine, euthanasia solution), sharps, medications, and biohazard — and how to handle each one right.",
    bullets: ["Deep-dive on every vet waste stream — what goes in, what doesn't, and why", "Controlled substances done right: ketamine, euthanasia solution, DEA Form 41", "A vet compliance checklist + the mistakes that fail DEA inspections", "A 'which kit for which stream' cheat sheet + a vet FAQ"],
    audience: "Veterinarians, practice managers, and techs at veterinary, equine, and shelter practices.",
    industry: "Veterinary",
    cover: "/images/guides/veterinary-practices.jpg",
  },
  {
    slug: "pharmacy-waste-disposal-guide",
    file: "/downloads/guides/pharmacies.pdf",
    eyebrow: "Free guide · for pharmacies",
    h1: "The Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "pharmacy waste disposal guide",
    title: "Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free pharmacy waste disposal guide — reverse distribution & credit recovery, controlled-substance returns (DEA Form 222/41), RCRA-hazardous drugs, and sharps: every stream a pharmacy handles, compliant and credit-smart.",
    intro: "A plain-English reference to every regulated waste stream your pharmacy handles — reverse distribution, controlled substances, RCRA-hazardous drugs, and sharps — plus how to recover manufacturer credit while destroying the rest compliantly.",
    bullets: ["Reverse distribution — recover credit on returnable Rx", "Controlled-substance returns: DEA Form 222/41, non-retrievable destruction", "Which drugs are RCRA-hazardous (P/U-listed) — and how to segregate them", "A pharmacy compliance checklist, cheat sheet & FAQ"],
    audience: "Pharmacists, pharmacy managers, and PICs at retail, independent, and chain pharmacies.",
    industry: "Pharmacy",
    cover: "/images/guides/pharmacies.jpg",
  },
  {
    slug: "med-spa-waste-disposal-guide",
    file: "/downloads/guides/med-spas.pdf",
    eyebrow: "Free guide · for med spas & aesthetics",
    h1: "The Med Spa's Guide to Compliant Waste Disposal",
    keyword: "med spa waste disposal guide",
    title: "Med Spa Waste Disposal Guide (Free Download)",
    desc: "Free med spa waste disposal guide — injection sharps, expired injectables (Botox, fillers), and PRP/blood biohazard: yes, your med spa generates regulated medical waste. Here's how to handle each stream compliantly.",
    intro: "A plain-English reference to every regulated waste stream your med spa generates — injection and microneedling sharps, expired injectables like neurotoxins and fillers, and blood-contaminated biohazard — and how to handle each one right.",
    bullets: ["Every med spa stream — sharps, expired injectables, PRP/blood waste", "How to dispose of expired Botox, fillers, and lidocaine", "Microneedling & PRP: what's a sharp, what's biohazard", "A med spa compliance checklist, cheat sheet & FAQ"],
    audience: "Med spa owners, injectors, and front-desk leads at aesthetic and wellness clinics.",
    industry: "Med Spa",
    cover: "/images/guides/med-spas.jpg",
  },
  {
    slug: "physician-office-waste-disposal-guide",
    file: "/downloads/guides/physician-offices.pdf",
    eyebrow: "Free guide · for physician offices",
    h1: "The Physician Office's Guide to Compliant Waste Disposal",
    keyword: "physician office medical waste disposal guide",
    title: "Physician Office Waste Disposal Guide (Free Download)",
    desc: "Free physician-office waste disposal guide — sharps, expired vaccines and medications, red-bag biohazard, and controlled substances: every regulated stream, the rules, and how to handle each compliantly.",
    intro: "A plain-English reference to every regulated waste stream your physician office generates — sharps, expired meds and vaccines, biohazard, and controlled substances — and how to handle each one right.",
    bullets: ["Every office stream — sharps, meds/vaccines, biohazard, controlled", "What's red-bag biohazard vs regular trash (and why it matters)", "A physician-office compliance checklist + FAQ", "A 'which kit for which stream' cheat sheet"],
    audience: "Physicians, office managers, and clinical staff at physician and specialty offices.",
    industry: "Physician Office",
    cover: "/images/guides/physician-offices.jpg",
  },
  {
    slug: "urgent-care-waste-disposal-guide",
    file: "/downloads/guides/urgent-care.pdf",
    eyebrow: "Free guide · for urgent care",
    h1: "The Urgent Care's Guide to Compliant Waste Disposal",
    keyword: "urgent care medical waste disposal guide",
    title: "Urgent Care Waste Disposal Guide (Free Download)",
    desc: "Free urgent-care waste disposal guide — high-volume sharps, red-bag biohazard, controlled pain meds, and expired medications: every regulated stream, mail-back or pickup, compliant every time.",
    intro: "A plain-English reference to every regulated waste stream your urgent care generates — high-volume sharps, biohazard, controlled substances, and expired meds — and how to handle each one right.",
    bullets: ["Every urgent-care stream — sharps, biohazard, controlled, pharma", "High-volume sharps: sizing kits vs scheduled pickup", "Controlled pain meds: non-retrievable + DEA Form 41", "A compliance checklist, cheat sheet & FAQ"],
    audience: "Medical directors, managers, and clinical staff at urgent care centers.",
    industry: "Urgent Care",
    cover: "/images/guides/urgent-care.jpg",
  },
  {
    slug: "trt-clinic-waste-disposal-guide",
    file: "/downloads/guides/trt-clinics.pdf",
    eyebrow: "Free guide · for TRT clinics",
    h1: "The TRT Clinic's Guide to Compliant Waste Disposal",
    keyword: "TRT clinic waste disposal guide",
    title: "TRT Clinic Waste Disposal Guide (Free Download)",
    desc: "Free TRT clinic waste disposal guide — testosterone is a Schedule III controlled substance. How to destroy wasted/expired testosterone (Form 41), handle injection sharps, and every other stream compliantly.",
    intro: "A plain-English reference to every regulated waste stream your TRT clinic generates — testosterone (a Schedule III controlled substance), injection sharps, expired hormones, and blood waste — and how to handle each right.",
    bullets: ["Testosterone is Schedule III — how to destroy it right (Form 41)", "Injection sharps and blood-draw waste", "Expired non-controlled hormones and ancillaries", "A TRT compliance checklist, cheat sheet & FAQ"],
    audience: "Owners, providers, and staff at TRT and hormone-optimization clinics.",
    industry: "TRT Clinic",
    cover: "/images/guides/trt-clinics.jpg",
  },
  {
    slug: "weight-loss-clinic-waste-disposal-guide",
    file: "/downloads/guides/weight-loss-glp1.pdf",
    eyebrow: "Free guide · for weight-loss & GLP-1 clinics",
    h1: "The Weight-Loss Clinic's Guide to Compliant Waste Disposal",
    keyword: "weight loss clinic waste disposal guide",
    title: "Weight-Loss & GLP-1 Clinic Waste Disposal Guide (Free Download)",
    desc: "Free weight-loss / GLP-1 clinic waste disposal guide — pen-needle sharps, expired semaglutide/tirzepatide, controlled appetite suppressants (phentermine), and biohazard: every stream, handled compliantly.",
    intro: "A plain-English reference to every regulated waste stream your weight-loss or GLP-1 clinic generates — pen-needle sharps, expired semaglutide/tirzepatide, controlled appetite suppressants, and biohazard — and how to handle each right.",
    bullets: ["GLP-1 pen needles & injection sharps — high volume", "Expired semaglutide / tirzepatide & compounded product", "Phentermine is Schedule IV — how to handle it", "A compliance checklist, cheat sheet & FAQ"],
    audience: "Owners, providers, and staff at weight-loss and GLP-1 clinics.",
    industry: "Weight Loss Clinic",
    cover: "/images/guides/weight-loss-glp1.jpg",
  },
  {
    slug: "iv-hydration-clinic-waste-disposal-guide",
    file: "/downloads/guides/iv-hydration-ketamine.pdf",
    eyebrow: "Free guide · for IV & ketamine clinics",
    h1: "The IV & Ketamine Clinic's Guide to Compliant Waste Disposal",
    keyword: "IV hydration ketamine clinic waste disposal guide",
    title: "IV & Ketamine Clinic Waste Disposal Guide (Free Download)",
    desc: "Free IV & ketamine clinic waste disposal guide — ketamine is a Schedule III controlled substance. How to destroy wasted/expired ketamine (Form 41), handle IV sharps, expired infusions, and biohazard compliantly.",
    intro: "A plain-English reference to every regulated waste stream your IV or ketamine clinic generates — ketamine (a Schedule III controlled substance), IV sharps, expired infusions and vitamins, and biohazard — and how to handle each right.",
    bullets: ["Ketamine is Schedule III — how to destroy it right (Form 41)", "IV catheters and injection sharps", "Expired IV meds and vitamins", "An IV clinic compliance checklist, cheat sheet & FAQ"],
    audience: "Owners, nurses, and providers at IV hydration and ketamine clinics.",
    industry: "IV Clinic",
    cover: "/images/guides/iv-hydration-ketamine.jpg",
  },
  {
    slug: "tattoo-studio-waste-disposal-guide",
    file: "/downloads/guides/tattoo.pdf",
    eyebrow: "Free guide · for tattoo & body-art studios",
    h1: "The Tattoo Studio's Guide to Compliant Waste Disposal",
    keyword: "tattoo studio waste disposal guide",
    title: "Tattoo Studio Waste Disposal Guide (Free Download)",
    desc: "Free tattoo studio waste disposal guide — used needles and blades are sharps, blood-contaminated materials are biohazard. Yes, your studio generates regulated medical waste. Here's how to handle each stream.",
    intro: "A plain-English reference to the regulated waste your tattoo studio generates — used needles and blades (sharps) and blood-contaminated materials (biohazard) — plus how to handle each and pass a health inspection.",
    bullets: ["Used needles, blades & cartridges — sharps handling", "Blood-contaminated wipes & ink caps — biohazard", "Expired numbing agents (lidocaine) — pharmaceutical", "A studio compliance checklist, cheat sheet & FAQ"],
    audience: "Tattoo and body-art studio owners and artists.",
    industry: "Tattoo Studio",
    cover: "/images/guides/tattoo.jpg",
  },
  {
    slug: "specialty-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/specialty-pharmacy.pdf",
    eyebrow: "Free guide · for specialty pharmacies",
    h1: "The Specialty Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "specialty pharmacy waste disposal guide",
    title: "Specialty Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free specialty pharmacy waste disposal guide — recover credit on high-cost biologics, handle hazardous & oncology drugs, controlled substances, and cold-chain product compliantly.",
    intro: "A plain-English reference to every regulated waste stream your specialty pharmacy handles — reverse distribution on high-cost biologics, hazardous drugs, controlled substances, and cold-chain product — and how to handle each right.",
    bullets: ["Recover credit on returnable high-cost biologics", "Hazardous & oncology drugs (RCRA / USP 800)", "Controlled substances: Form 222/41, non-retrievable", "A specialty pharmacy checklist, cheat sheet & FAQ"],
    audience: "Owners, PICs, and compliance leads at specialty pharmacies.",
    industry: "Specialty Pharmacy",
    cover: "/images/guides/specialty-pharmacy.jpg",
  },
  {
    slug: "mail-order-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/mail-order-pharmacy.pdf",
    eyebrow: "Free guide · for mail-order pharmacies",
    h1: "The Mail-Order Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "mail order pharmacy waste disposal guide",
    title: "Mail-Order Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free mail-order pharmacy waste disposal guide — systematic reverse distribution and destruction at volume: recover credit, handle controlled and hazardous drugs, stay compliant.",
    intro: "A plain-English reference to every regulated waste stream your mail-order pharmacy handles at volume — reverse distribution, controlled substances, hazardous drugs, and non-hazardous Rx — and how to recover credit while destroying the rest compliantly.",
    bullets: ["Systematic reverse distribution at volume — recover credit", "Controlled substances: Form 222/41, non-retrievable", "Hazardous drugs (P/U-listed) — segregate at scale", "A mail-order pharmacy checklist, cheat sheet & FAQ"],
    audience: "Operations and compliance leads at mail-order pharmacies.",
    industry: "Mail-Order Pharmacy",
    cover: "/images/guides/mail-order-pharmacy.jpg",
  },
  {
    slug: "340b-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/340b-pharmacy.pdf",
    eyebrow: "Free guide · for 340B pharmacies",
    h1: "The 340B Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "340B pharmacy waste disposal guide",
    title: "340B Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free 340B pharmacy waste disposal guide — recover credit through reverse distribution and keep the audit-ready records 340B compliance demands. Controlled, hazardous, and non-hazardous streams covered.",
    intro: "A plain-English reference to every regulated waste stream your 340B pharmacy handles — reverse distribution for credit plus audit-ready records, controlled substances, hazardous drugs, and non-hazardous Rx.",
    bullets: ["Reverse distribution — credit plus audit-ready return records", "Controlled substances: Form 222/41 documentation", "Hazardous drugs (P/U-listed) — identified & documented", "A 340B compliance checklist, cheat sheet & FAQ"],
    audience: "340B program managers, PICs, and compliance leads.",
    industry: "340B Pharmacy",
    cover: "/images/guides/340b-pharmacy.jpg",
  },
  {
    slug: "503b-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/503b-pharmacy.pdf",
    eyebrow: "Free guide · for 503B outsourcing facilities",
    h1: "The 503B Facility's Guide to Compliant Waste Disposal",
    keyword: "503B waste disposal guide",
    title: "503B Facility Waste Disposal Guide (Free Download)",
    desc: "Free 503B waste disposal guide — sterile compounding and batch waste, hazardous APIs and chemo (USP 800), and controlled substances: a compounder's waste, handled to cGMP and EPA standards.",
    intro: "A plain-English reference to a 503B outsourcing facility's regulated waste — sterile compounding and batch waste, hazardous APIs and chemotherapy, controlled substances, and non-hazardous compounding waste — and how to handle each right.",
    bullets: ["Failed / expired batches & cleanroom waste", "Hazardous APIs & chemo (RCRA / USP 800)", "Controlled compounding waste (Form 41)", "A 503B checklist, cheat sheet & FAQ"],
    audience: "Quality, operations, and compliance leads at 503B outsourcing facilities.",
    industry: "503B Facility",
    cover: "/images/guides/503b-pharmacy.jpg",
  },
  {
    slug: "closed-door-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/closed-door-pharmacy.pdf",
    eyebrow: "Free guide · for closed-door & LTC pharmacies",
    h1: "The Closed-Door Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "closed door pharmacy waste disposal guide",
    title: "Closed-Door Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free closed-door / LTC pharmacy waste disposal guide — resident medication returns, blister-pack waste, and controlled substances with audit-ready, chain-of-custody destruction.",
    intro: "A plain-English reference to every regulated waste stream your closed-door / LTC pharmacy handles — resident controlled returns, blister-pack and unit-dose waste, reverse distribution, and hazardous drugs — and how to handle each right.",
    bullets: ["Resident controlled returns: Form 41 + chain-of-custody", "Blister-pack & unit-dose returns", "Reverse distribution — recover credit on returnable stock", "A closed-door pharmacy checklist, cheat sheet & FAQ"],
    audience: "PICs, consultant pharmacists, and compliance leads at closed-door / LTC pharmacies.",
    industry: "Closed-Door Pharmacy",
    cover: "/images/guides/closed-door-pharmacy.jpg",
  },
  {
    slug: "correctional-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/correctional-pharmacy.pdf",
    eyebrow: "Free guide · for correctional pharmacies",
    h1: "The Correctional Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "correctional pharmacy waste disposal guide",
    title: "Correctional Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free correctional pharmacy waste disposal guide — secure, documented chain-of-custody destruction for controlled substances and pharmacy waste in diversion-sensitive settings.",
    intro: "A plain-English reference to every regulated waste stream your correctional pharmacy handles — controlled substances with secure chain-of-custody, non-controlled and hazardous drugs, and reverse distribution — and how to handle each right.",
    bullets: ["Secure chain-of-custody controlled destruction (Form 41)", "Non-controlled & hazardous drug destruction", "Reverse distribution — recover credit", "A correctional pharmacy checklist, cheat sheet & FAQ"],
    audience: "Pharmacy directors and compliance leads in correctional healthcare.",
    industry: "Correctional Pharmacy",
    cover: "/images/guides/correctional-pharmacy.jpg",
  },
  {
    slug: "surgery-center-waste-disposal-guide",
    file: "/downloads/guides/asc.pdf",
    eyebrow: "Free guide · for surgery centers",
    h1: "The Surgery Center's Guide to Compliant Waste Disposal",
    keyword: "surgery center waste disposal guide",
    title: "Surgery Center Waste Disposal Guide (Free Download)",
    desc: "Free ambulatory surgery center waste disposal guide — high-volume anesthesia controlled substances (fentanyl, midazolam), surgical sharps, biohazard, and meds: every stream, mail-back or pickup, compliant.",
    intro: "A plain-English reference to every regulated waste stream your ambulatory surgery center generates — anesthesia controlled substances, surgical sharps, biohazard, and expired meds — and how to handle each right.",
    bullets: ["Anesthesia controls (fentanyl, midazolam): wasting logs + Form 41", "High-volume surgical sharps and biohazard", "Expired non-controlled medications", "An ASC compliance checklist, cheat sheet & FAQ"],
    audience: "Administrators, DONs, and clinical staff at ambulatory surgery centers.",
    industry: "Surgery Center",
    cover: "/images/guides/asc.jpg",
  },
  {
    slug: "hospital-waste-disposal-guide",
    file: "/downloads/guides/hospitals.pdf",
    eyebrow: "Free guide · for hospitals & health systems",
    h1: "The Hospital's Guide to Compliant Waste Disposal",
    keyword: "hospital medical waste disposal guide",
    title: "Hospital Waste Disposal Guide (Free Download)",
    desc: "Free hospital & health-system waste disposal guide — every regulated stream at scale: controlled substances, sharps, biohazard, RCRA-hazardous, USP 800 chemo, centralized and documented.",
    intro: "A plain-English reference to every regulated waste stream a hospital or health system generates — controlled substances, sharps, biohazard, RCRA-hazardous, and USP 800 chemo — and how to centralize and document each.",
    bullets: ["Every stream at scale — controlled, sharps, RMW, RCRA, chemo", "Centralized, defensible controlled-substance destruction", "USP 800 chemo & RCRA-hazardous handling", "A hospital compliance checklist, cheat sheet & FAQ"],
    audience: "Environmental services, pharmacy, and compliance leaders at hospitals and health systems.",
    industry: "Hospital",
    cover: "/images/guides/hospitals.jpg",
  },
  {
    slug: "academic-medical-center-waste-disposal-guide",
    file: "/downloads/guides/academic-medical-centers.pdf",
    eyebrow: "Free guide · for academic medical centers",
    h1: "The Academic Medical Center's Guide to Compliant Waste Disposal",
    keyword: "academic medical center waste disposal guide",
    title: "Academic Medical Center Waste Disposal Guide (Free Download)",
    desc: "Free academic medical center waste disposal guide — clinical care plus research: controlled substances, clinical & research biohazard, RCRA-hazardous chemicals, and chemo, coordinated under one program.",
    intro: "A plain-English reference to every regulated waste stream an academic medical center generates — clinical and research biohazard, controlled substances, hazardous chemicals, and chemo — and how to coordinate them.",
    bullets: ["Clinical + research waste under one program", "Lab controlled substances & hazardous chemicals", "USP 800 chemo & RCRA handling", "An AMC compliance checklist, cheat sheet & FAQ"],
    audience: "Compliance, EHS, and pharmacy leaders at academic medical centers.",
    industry: "Academic Medical Center",
    cover: "/images/guides/academic-medical-centers.jpg",
  },
  {
    slug: "oncology-infusion-waste-disposal-guide",
    file: "/downloads/guides/oncology-infusion.pdf",
    eyebrow: "Free guide · for oncology & infusion centers",
    h1: "The Oncology & Infusion Center's Guide to Compliant Waste Disposal",
    keyword: "chemotherapy waste disposal guide",
    title: "Oncology & Infusion Waste Disposal Guide (Free Download)",
    desc: "Free oncology & infusion center waste disposal guide — trace and bulk chemotherapy under USP 800, plus infusion sharps, controlled supportive-care drugs, and biohazard: every stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream your oncology or infusion center generates — trace and bulk chemo (USP 800), infusion sharps, controlled supportive-care drugs, and biohazard — and how to handle each.",
    bullets: ["Trace vs bulk chemo — the USP 800 distinction that matters", "Infusion sharps and access-port waste", "Controlled supportive-care drugs: Form 41", "An oncology checklist, cheat sheet & FAQ"],
    audience: "Oncology pharmacists, nurses, and compliance leads at infusion centers.",
    industry: "Oncology / Infusion",
    cover: "/images/guides/oncology-infusion.jpg",
  },
  {
    slug: "dialysis-center-waste-disposal-guide",
    file: "/downloads/guides/dialysis.pdf",
    eyebrow: "Free guide · for dialysis centers",
    h1: "The Dialysis Center's Guide to Compliant Waste Disposal",
    keyword: "dialysis waste disposal guide",
    title: "Dialysis Center Waste Disposal Guide (Free Download)",
    desc: "Free dialysis center waste disposal guide — high-volume fistula-access sharps and blood-contaminated biohazard, plus expired heparin and ESAs: every stream, sized to your volume.",
    intro: "A plain-English reference to every regulated waste stream your dialysis center generates — high-volume fistula sharps, blood-contaminated biohazard, and expired meds — and how to handle each at volume.",
    bullets: ["High-volume fistula sharps — sizing so you never overfill", "Blood-contaminated biohazard", "Expired heparin and ESAs", "A dialysis checklist, cheat sheet & FAQ"],
    audience: "Clinic managers and nurses at dialysis centers.",
    industry: "Dialysis Center",
    cover: "/images/guides/dialysis.jpg",
  },
  {
    slug: "dental-dso-waste-disposal-guide",
    file: "/downloads/guides/dental-groups-dso.pdf",
    eyebrow: "Free guide · for dental groups & DSOs",
    h1: "The Dental Group / DSO Guide to Compliant Waste Disposal",
    keyword: "dental DSO waste disposal guide",
    title: "Dental Group / DSO Waste Disposal Guide (Free Download)",
    desc: "Free dental group / DSO waste disposal guide — standardize sharps, amalgam, pharmaceutical, biohazard, and controlled disposal across every location, with centralized records.",
    intro: "A plain-English reference to standardizing dental waste across a group or DSO — sharps, amalgam, pharmaceutical, biohazard, and controlled — with one process and centralized records at every location.",
    bullets: ["Standardize every stream across every location", "Amalgam compliance at scale (EPA rule) — audit each site", "Centralized Certificates of Destruction & billing", "A DSO compliance checklist, cheat sheet & FAQ"],
    audience: "Operations, compliance, and clinical leaders at dental groups and DSOs.",
    industry: "Dental Group / DSO",
    cover: "/images/guides/dental-groups-dso.jpg",
  },
  {
    slug: "dermatology-waste-disposal-guide",
    file: "/downloads/guides/dermatology.pdf",
    eyebrow: "Free guide · for dermatology",
    h1: "The Dermatology Practice's Guide to Compliant Waste Disposal",
    keyword: "dermatology waste disposal guide",
    title: "Dermatology Waste Disposal Guide (Free Download)",
    desc: "Free dermatology waste disposal guide — biopsy and Mohs sharps, tissue biohazard, and hazardous topical chemo (5-FU): every regulated stream, including the ones practices miss.",
    intro: "A plain-English reference to every regulated waste stream your dermatology practice generates — biopsy and Mohs sharps, tissue biohazard, expired meds, and hazardous topical chemo — and how to handle each right.",
    bullets: ["Biopsy, excision & Mohs sharps", "Topical chemo (5-FU) is hazardous — how to handle it", "Tissue & biopsy biohazard", "A dermatology checklist, cheat sheet & FAQ"],
    audience: "Dermatologists, office managers, and staff at dermatology and Mohs practices.",
    industry: "Dermatology",
    cover: "/images/guides/dermatology.jpg",
  },
  {
    slug: "podiatry-waste-disposal-guide",
    file: "/downloads/guides/podiatry.pdf",
    eyebrow: "Free guide · for podiatry",
    h1: "The Podiatry Practice's Guide to Compliant Waste Disposal",
    keyword: "podiatry waste disposal guide",
    title: "Podiatry Waste Disposal Guide (Free Download)",
    desc: "Free podiatry waste disposal guide — surgical and injection sharps, wound-care and nail-procedure biohazard, and expired meds: every regulated stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream your podiatry practice generates — surgical and injection sharps, wound-care biohazard, and expired meds — and how to handle each right.",
    bullets: ["Surgical, injection & nail-procedure sharps", "Wound-care biohazard — what's regulated", "Expired anesthetics & meds", "A podiatry checklist, cheat sheet & FAQ"],
    audience: "Podiatrists, office managers, and clinical staff.",
    industry: "Podiatry",
    cover: "/images/guides/podiatry.jpg",
  },
  {
    slug: "plastic-surgery-waste-disposal-guide",
    file: "/downloads/guides/plastic-surgery.pdf",
    eyebrow: "Free guide · for plastic surgery",
    h1: "The Plastic Surgery Practice's Guide to Compliant Waste Disposal",
    keyword: "plastic surgery waste disposal guide",
    title: "Plastic Surgery Waste Disposal Guide (Free Download)",
    desc: "Free plastic surgery waste disposal guide — anesthesia controlled substances, surgical sharps, tissue biohazard, and expired injectables: every regulated stream, handled to DEA standards.",
    intro: "A plain-English reference to every regulated waste stream your plastic surgery practice generates — anesthesia controls, surgical sharps, tissue biohazard, and expired injectables — and how to handle each right.",
    bullets: ["Anesthesia controls: wasting logs + Form 41", "Surgical & injection sharps", "Surgical/liposuction tissue biohazard", "A plastic surgery checklist, cheat sheet & FAQ"],
    audience: "Plastic surgeons, administrators, and clinical staff.",
    industry: "Plastic Surgery",
    cover: "/images/guides/plastic-surgery.jpg",
  },
  {
    slug: "pain-management-waste-disposal-guide",
    file: "/downloads/guides/pain-management.pdf",
    eyebrow: "Free guide · for pain management",
    h1: "The Pain Management Clinic's Guide to Compliant Waste Disposal",
    keyword: "pain management waste disposal guide",
    title: "Pain Management Waste Disposal Guide (Free Download)",
    desc: "Free pain management waste disposal guide — controlled substances (opioids, sedatives) are the whole game: non-retrievable destruction, Form 41, wasting logs, plus procedure sharps and biohazard.",
    intro: "A plain-English reference to every regulated waste stream your pain management clinic generates — controlled substances, procedure sharps, expired meds, and biohazard — and how to handle each right.",
    bullets: ["Opioids & controlled substances: Form 41 + wasting logs", "The DEA scrutiny this specialty gets — and how to pass", "Procedure & injection sharps", "A pain management checklist, cheat sheet & FAQ"],
    audience: "Pain management physicians, administrators, and compliance staff.",
    industry: "Pain Management",
    cover: "/images/guides/pain-management.jpg",
  },
  {
    slug: "fertility-ivf-waste-disposal-guide",
    file: "/downloads/guides/fertility-ivf.pdf",
    eyebrow: "Free guide · for fertility & IVF clinics",
    h1: "The Fertility / IVF Clinic's Guide to Compliant Waste Disposal",
    keyword: "fertility IVF waste disposal guide",
    title: "Fertility & IVF Clinic Waste Disposal Guide (Free Download)",
    desc: "Free fertility & IVF clinic waste disposal guide — high-volume injection sharps, expired hormones, and retrieval/andrology-lab biohazard: every regulated stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream your fertility or IVF clinic generates — injection sharps, expired hormones, and lab biohazard — and how to handle each right.",
    bullets: ["High-volume injection sharps (self-injection support)", "Expired hormones — gonadotropins, hCG, progesterone", "Retrieval & andrology-lab biohazard", "A fertility clinic checklist, cheat sheet & FAQ"],
    audience: "Fertility physicians, nurses, and lab and office managers.",
    industry: "Fertility / IVF",
    cover: "/images/guides/fertility-ivf.jpg",
  },
  {
    slug: "endoscopy-gi-waste-disposal-guide",
    file: "/downloads/guides/endoscopy-gi.pdf",
    eyebrow: "Free guide · for endoscopy & GI centers",
    h1: "The Endoscopy & GI Center's Guide to Compliant Waste Disposal",
    keyword: "endoscopy GI waste disposal guide",
    title: "Endoscopy & GI Center Waste Disposal Guide (Free Download)",
    desc: "Free endoscopy & GI center waste disposal guide — sedation controlled substances, biopsy sharps and tissue, and scope-reprocessing disinfectants (glutaraldehyde/OPA): every stream, including the overlooked ones.",
    intro: "A plain-English reference to every regulated waste stream your endoscopy or GI center generates — sedation controls, biopsy sharps and tissue, and scope-reprocessing chemicals — and how to handle each right.",
    bullets: ["Sedation controls (fentanyl, midazolam): Form 41", "Biopsy sharps & tissue biohazard", "Scope disinfectants (glutaraldehyde/OPA) — often hazardous", "An endoscopy checklist, cheat sheet & FAQ"],
    audience: "GI physicians, endoscopy nurses, and center administrators.",
    industry: "Endoscopy / GI",
    cover: "/images/guides/endoscopy-gi.jpg",
  },
  {
    slug: "allergy-clinic-waste-disposal-guide",
    file: "/downloads/guides/allergy-immunotherapy.pdf",
    eyebrow: "Free guide · for allergy & immunotherapy",
    h1: "The Allergy Clinic's Guide to Compliant Waste Disposal",
    keyword: "allergy clinic waste disposal guide",
    title: "Allergy Clinic Waste Disposal Guide (Free Download)",
    desc: "Free allergy & immunotherapy clinic waste disposal guide — high-volume allergy-shot sharps, expired serums, and P-listed epinephrine (a hazardous waste clinics miss): every stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream your allergy or immunotherapy clinic generates — high-volume shot sharps, expired serums, and P-listed epinephrine — and how to handle each right.",
    bullets: ["High-volume allergy-shot sharps", "Epinephrine is P-listed hazardous — how to handle it", "Expired allergen serums & extracts", "An allergy clinic checklist, cheat sheet & FAQ"],
    audience: "Allergists, nurses, and office managers at allergy and immunotherapy clinics.",
    industry: "Allergy / Immunotherapy",
    cover: "/images/guides/allergy-immunotherapy.jpg",
  },
  {
    slug: "nursing-home-waste-disposal-guide",
    file: "/downloads/guides/nursing-homes.pdf",
    eyebrow: "Free guide · for nursing homes & LTC",
    h1: "The Nursing Home / LTC Guide to Compliant Waste Disposal",
    keyword: "nursing home waste disposal guide",
    title: "Nursing Home / LTC Waste Disposal Guide (Free Download)",
    desc: "Free nursing home / LTC waste disposal guide — unused resident controlled substances, med returns, insulin sharps, and biohazard: safe, documented destruction by mail-back or on-site deactivation.",
    intro: "A plain-English reference to every regulated waste stream your nursing home or LTC facility generates — unused resident controls, med returns, insulin sharps, and biohazard — and how to handle each right.",
    bullets: ["Unused resident controls: mail-back or on-site deactivation + Form 41", "Blister-pack & unit-dose med returns", "Insulin & injection sharps", "An LTC compliance checklist, cheat sheet & FAQ"],
    audience: "Directors of nursing, consultant pharmacists, and administrators at LTC facilities.",
    industry: "Nursing Home / LTC",
    cover: "/images/guides/nursing-homes.jpg",
  },
  {
    slug: "hospice-waste-disposal-guide",
    file: "/downloads/guides/hospice.pdf",
    eyebrow: "Free guide · for hospice",
    h1: "The Hospice Guide to Compliant Waste Disposal",
    keyword: "hospice medication disposal guide",
    title: "Hospice Waste Disposal Guide (Free Download)",
    desc: "Free hospice waste disposal guide — safely destroy unused opioids and controlled substances after a patient passes (on-site deactivation or mail-back, Form 41), plus sharps and every stream.",
    intro: "A plain-English reference to every regulated waste stream hospice care generates — unused opioids and controls after a patient passes, sharps, and medications — and how to handle each right.",
    bullets: ["Unused opioids after death: on-site deactivation or mail-back", "DEA Form 41 & diversion prevention", "In-home & facility sharps", "A hospice compliance checklist, cheat sheet & FAQ"],
    audience: "Hospice clinical directors, nurses, and compliance leads.",
    industry: "Hospice",
    cover: "/images/guides/hospice.jpg",
  },
  {
    slug: "home-health-waste-disposal-guide",
    file: "/downloads/guides/home-health.pdf",
    eyebrow: "Free guide · for home health agencies",
    h1: "The Home Health Agency's Guide to Compliant Waste Disposal",
    keyword: "home health waste disposal guide",
    title: "Home Health Waste Disposal Guide (Free Download)",
    desc: "Free home health waste disposal guide — mail-back kits for distributed, in-home sharps and medications, plus on-site deactivation for controls: compliant disposal, house to house.",
    intro: "A plain-English reference to every regulated waste stream your home health agency generates across patient homes — in-home sharps, patient medications and controls, and wound-care biohazard — and how to handle each right.",
    bullets: ["In-home sharps: prepaid mail-back kits, house to house", "Patient controls: on-site deactivation or mail-back (Form 41)", "Expired & discontinued patient meds", "A home health checklist, cheat sheet & FAQ"],
    audience: "Home health agency directors, clinicians, and compliance leads.",
    industry: "Home Health",
    cover: "/images/guides/home-health.jpg",
  },
  {
    slug: "group-home-waste-disposal-guide",
    file: "/downloads/guides/group-homes.pdf",
    eyebrow: "Free guide · for group homes",
    h1: "The Group Home's Guide to Compliant Waste Disposal",
    keyword: "group home medication disposal guide",
    title: "Group Home Waste Disposal Guide (Free Download)",
    desc: "Free group home waste disposal guide — safe, documented resident medication take-back including controlled substances (mail-back or on-site deactivation), plus insulin sharps.",
    intro: "A plain-English reference to every regulated waste stream your group home generates — resident controlled substances, med returns, and insulin sharps — and how to handle each right.",
    bullets: ["Resident controls: on-site deactivation or mail-back + Form 41", "Resident non-controlled med returns", "Insulin & injection sharps", "A group home checklist, cheat sheet & FAQ"],
    audience: "Group home administrators and residential-care staff.",
    industry: "Group Home",
    cover: "/images/guides/group-homes.jpg",
  },
  {
    slug: "school-health-waste-disposal-guide",
    file: "/downloads/guides/school-health.pdf",
    eyebrow: "Free guide · for school & K-12 health",
    h1: "The School Health Office's Guide to Compliant Waste Disposal",
    keyword: "school nurse waste disposal guide",
    title: "School Health Waste Disposal Guide (Free Download)",
    desc: "Free school health waste disposal guide — student sharps, expired EpiPens (P-listed hazardous waste), and unclaimed student medications: every stream, including the one schools miss.",
    intro: "A plain-English reference to every regulated waste stream a school health office generates — student sharps, expired EpiPens, and unclaimed medications — and how to handle each right.",
    bullets: ["Student diabetic & emergency sharps", "Expired EpiPens are P-listed hazardous — how to handle them", "Unclaimed & year-end student medications", "A school health checklist, cheat sheet & FAQ"],
    audience: "School nurses, district health coordinators, and administrators.",
    industry: "School Health",
    cover: "/images/guides/school-health.jpg",
  },
  {
    slug: "correctional-facility-waste-disposal-guide",
    file: "/downloads/guides/correctional.pdf",
    eyebrow: "Free guide · for correctional facilities",
    h1: "The Correctional Facility's Guide to Compliant Waste Disposal",
    keyword: "correctional facility waste disposal guide",
    title: "Correctional Facility Waste Disposal Guide (Free Download)",
    desc: "Free correctional facility waste disposal guide — secure, documented chain-of-custody destruction for infirmary controlled substances, sharps, and biohazard in diversion-sensitive settings.",
    intro: "A plain-English reference to every regulated waste stream a correctional facility infirmary generates — controlled substances with secure chain-of-custody, sharps, biohazard, and meds — and how to handle each right.",
    bullets: ["Secure chain-of-custody controlled destruction (Form 41)", "On-site deactivation for added security", "Infirmary sharps & biohazard", "A correctional compliance checklist, cheat sheet & FAQ"],
    audience: "Correctional healthcare administrators and infirmary staff.",
    industry: "Correctional Facility",
    cover: "/images/guides/correctional.jpg",
  },
  {
    slug: "optometry-waste-disposal-guide",
    file: "/downloads/guides/optometry.pdf",
    eyebrow: "Free guide · for optometry",
    h1: "The Optometry Practice's Guide to Compliant Waste Disposal",
    keyword: "optometry waste disposal guide",
    title: "Optometry Waste Disposal Guide (Free Download)",
    desc: "Free optometry waste disposal guide — expired diagnostic and dilating drops and the occasional sharp: low-waste, not no-waste, handled simply with prepaid mail-back kits.",
    intro: "A short, plain-English reference to the regulated waste an optometry practice actually generates — expired diagnostic and dilating drops and occasional sharps — and the simplest compliant way to handle it.",
    bullets: ["Expired dilating & diagnostic drops — how to dispose", "The occasional injection or diagnostic sharp", "Right-sized, low-volume mail-back kits", "An optometry checklist, cheat sheet & FAQ"],
    audience: "Optometrists and office managers at optometry practices.",
    industry: "Optometry",
    cover: "/images/guides/optometry.jpg",
  },
  {
    slug: "ophthalmology-waste-disposal-guide",
    file: "/downloads/guides/ophthalmology.pdf",
    eyebrow: "Free guide · for ophthalmology",
    h1: "The Ophthalmology Practice's Guide to Compliant Waste Disposal",
    keyword: "ophthalmology waste disposal guide",
    title: "Ophthalmology Waste Disposal Guide (Free Download)",
    desc: "Free ophthalmology waste disposal guide — intravitreal injection and surgical sharps, expired injectable drugs (anti-VEGF, anesthetics), and biohazard: every stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream your ophthalmology practice generates — injection and surgical sharps, expired injectables, and biohazard — and how to handle each right.",
    bullets: ["Intravitreal injection & surgical sharps", "Expired anti-VEGF & injectable drugs", "Surgical & procedure biohazard", "An ophthalmology checklist, cheat sheet & FAQ"],
    audience: "Ophthalmologists, surgical staff, and practice administrators.",
    industry: "Ophthalmology",
    cover: "/images/guides/ophthalmology.jpg",
  },
  {
    slug: "chiropractic-waste-disposal-guide",
    file: "/downloads/guides/chiropractic.pdf",
    eyebrow: "Free guide · for chiropractic",
    h1: "The Chiropractic Office's Guide to Compliant Waste Disposal",
    keyword: "chiropractic waste disposal guide",
    title: "Chiropractic Waste Disposal Guide (Free Download)",
    desc: "Free chiropractic waste disposal guide — do you even generate regulated waste? If you do dry needling, trigger-point injections, or lab draws, here's exactly what applies and how to comply.",
    intro: "A short, plain-English reference that tells you when medical-waste rules actually apply to a chiropractic office — dry needling, injections, lab draws — and the simplest way to comply if they do.",
    bullets: ["When (and whether) the rules apply to you", "Dry-needling & trigger-point injection sharps", "Low-volume, low-cost mail-back kits", "A chiropractic checklist, cheat sheet & FAQ"],
    audience: "Chiropractors and office managers, including practices that offer dry needling.",
    industry: "Chiropractic",
    cover: "/images/guides/chiropractic.jpg",
  },
  {
    slug: "acupuncture-waste-disposal-guide",
    file: "/downloads/guides/acupuncture.pdf",
    eyebrow: "Free guide · for acupuncture",
    h1: "The Acupuncture Clinic's Guide to Compliant Waste Disposal",
    keyword: "acupuncture needle disposal guide",
    title: "Acupuncture Waste Disposal Guide (Free Download)",
    desc: "Free acupuncture waste disposal guide — single-use needles are your one main regulated stream, but the volume adds up: how to dispose of them compliantly with right-sized mail-back kits.",
    intro: "A short, plain-English reference to acupuncture's main regulated waste stream — single-use needles — plus contaminated cotton, and the simplest compliant way to handle the volume.",
    bullets: ["Single-use needle disposal, done right", "Sizing sharps kits to your treatment volume", "Blood-spotted cotton — when it's regulated", "An acupuncture checklist, cheat sheet & FAQ"],
    audience: "Acupuncturists and clinic managers.",
    industry: "Acupuncture",
    cover: "/images/guides/acupuncture.jpg",
  },
  {
    slug: "retail-clinic-waste-disposal-guide",
    file: "/downloads/guides/retail-clinics.pdf",
    eyebrow: "Free guide · for retail & walk-in clinics",
    h1: "The Retail / Walk-In Clinic's Guide to Compliant Waste Disposal",
    keyword: "retail clinic waste disposal guide",
    title: "Retail & Walk-In Clinic Waste Disposal Guide (Free Download)",
    desc: "Free retail & walk-in clinic waste disposal guide — vaccine and injection sharps and expired vaccines drive the volume: one standardized, documented program across every location.",
    intro: "A plain-English reference to every regulated waste stream your retail or walk-in clinic generates — vaccine and injection sharps, expired vaccines and meds — and how to standardize it across sites.",
    bullets: ["Vaccine & injection sharps — managing the volume", "Expired vaccines & medications", "One consistent program across every location", "A retail-clinic checklist, cheat sheet & FAQ"],
    audience: "Retail and walk-in clinic operators, managers, and multi-site administrators.",
    industry: "Retail / Walk-In Clinic",
    cover: "/images/guides/retail-clinics.jpg",
  },
  {
    slug: "fqhc-waste-disposal-guide",
    file: "/downloads/guides/fqhc.pdf",
    eyebrow: "Free guide · for FQHCs & community health centers",
    h1: "The FQHC / Community Health Center's Guide to Compliant Waste Disposal",
    keyword: "FQHC waste disposal guide",
    title: "FQHC & Community Health Center Waste Disposal Guide (Free Download)",
    desc: "Free FQHC waste disposal guide — the full range of regulated waste across medical, dental, behavioral health, and pharmacy (including 340B), handled affordably with no contract and no minimums.",
    intro: "A plain-English reference to every regulated waste stream an FQHC or community health center generates across departments — sharps, pharma (including 340B), controls, and biohazard — handled on a grant budget.",
    bullets: ["Every stream, across every department", "Expired 340B medications — how to handle them", "Controlled substances: Form 41", "No contract, no minimums — grant-budget friendly"],
    audience: "FQHC and community health center administrators, pharmacists, and compliance leads.",
    industry: "FQHC / Community Health",
    cover: "/images/guides/fqhc.jpg",
  },
  {
    slug: "research-lab-waste-disposal-guide",
    file: "/downloads/guides/research-labs.pdf",
    eyebrow: "Free guide · for research & academic labs",
    h1: "The Research Lab's Guide to Compliant Waste Disposal",
    keyword: "research lab waste disposal guide",
    title: "Research Lab Waste Disposal Guide (Free Download)",
    desc: "Free research lab waste disposal guide — hazardous chemicals, biologicals, sharps (including broken glass), and research controlled substances: four streams, four rulebooks, characterized right.",
    intro: "A plain-English reference to every regulated waste stream a research or academic lab generates — hazardous chemicals, biologicals, sharps, and research controls — and how to characterize and route each.",
    bullets: ["Hazardous chemicals: characterize & manifest", "Biological & culture waste", "Sharps, broken glass & pipette tips", "Research controlled substances (Form 41)"],
    audience: "Lab managers, PIs, and EH&S staff at research and academic labs.",
    industry: "Research / Academic Lab",
    cover: "/images/guides/research-labs.jpg",
  },
  {
    slug: "clinical-lab-waste-disposal-guide",
    file: "/downloads/guides/clinical-labs.pdf",
    eyebrow: "Free guide · for clinical & diagnostic labs",
    h1: "The Clinical Lab's Guide to Compliant Waste Disposal",
    keyword: "clinical lab waste disposal guide",
    title: "Clinical Lab Waste Disposal Guide (Free Download)",
    desc: "Free clinical lab waste disposal guide — specimen and culture biohazard, high-volume phlebotomy sharps, hazardous stains and fixatives, and pathology/tissue: every stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream a clinical or diagnostic lab generates — specimen biohazard, phlebotomy sharps, hazardous reagents, and tissue — and how to handle each.",
    bullets: ["Specimen & culture biohazard", "High-volume phlebotomy sharps", "Hazardous stains, fixatives & reagents", "Tissue/pathology waste — state rules"],
    audience: "Lab directors, managers, and safety officers at clinical and diagnostic labs.",
    industry: "Clinical / Diagnostic Lab",
    cover: "/images/guides/clinical-labs.jpg",
  },
  {
    slug: "blood-plasma-center-waste-disposal-guide",
    file: "/downloads/guides/blood-plasma.pdf",
    eyebrow: "Free guide · for blood & plasma centers",
    h1: "The Blood / Plasma Center's Guide to Compliant Waste Disposal",
    keyword: "blood plasma center waste disposal guide",
    title: "Blood & Plasma Center Waste Disposal Guide (Free Download)",
    desc: "Free blood & plasma center waste disposal guide — high-volume phlebotomy sharps and blood-contaminated biohazard (tubing, bags, units) on a cadence built for donation throughput.",
    intro: "A plain-English reference to every regulated waste stream a blood or plasma donation center generates — high-volume phlebotomy sharps and blood biohazard — and how to keep a busy floor compliant.",
    bullets: ["High-volume phlebotomy sharps", "Blood-contaminated tubing, bags & units", "A pickup cadence sized to throughput", "A donation-center checklist, cheat sheet & FAQ"],
    audience: "Donation center managers and quality staff at blood and plasma centers.",
    industry: "Blood / Plasma Center",
    cover: "/images/guides/blood-plasma.jpg",
  },
  {
    slug: "clinical-trial-waste-disposal-guide",
    file: "/downloads/guides/clinical-trials.pdf",
    eyebrow: "Free guide · for clinical trial sites & sponsors",
    h1: "The Clinical Trial Site's Guide to Compliant Waste Disposal",
    keyword: "clinical trial drug destruction guide",
    title: "Clinical Trial Waste & IP Destruction Guide (Free Download)",
    desc: "Free clinical trial waste disposal guide — investigational product destruction with an auditable chain of custody for sponsors, monitors, and the FDA, plus controls, study sharps, and biohazard.",
    intro: "A plain-English reference to every regulated waste stream a clinical trial site generates — investigational product destruction, controls, study sharps, and biohazard — with the documentation monitors expect.",
    bullets: ["Investigational product destruction: chain of custody", "Controlled IP (Form 41)", "Study sharps & specimen biohazard", "Audit-ready documentation for monitors & FDA"],
    audience: "Clinical research coordinators, site managers, pharmacists, and sponsors.",
    industry: "Clinical Trials",
    cover: "/images/guides/clinical-trials.jpg",
  },
  {
    slug: "pharma-manufacturer-product-destruction-guide",
    file: "/downloads/guides/pharma-manufacturers.pdf",
    eyebrow: "Free guide · for manufacturers & distributors",
    h1: "The Manufacturer / Distributor's Guide to Compliant Product Destruction",
    keyword: "pharmaceutical product destruction guide",
    title: "Manufacturer & Distributor Product Destruction Guide (Free Download)",
    desc: "Free manufacturer product destruction guide — expired, off-spec, recalled, and returned product destroyed at scale, including registrant-to-registrant controlled destruction, with manifests and chain of custody.",
    intro: "A plain-English reference to compliant product destruction for pharmaceutical manufacturers and distributors — bulk expired/off-spec/recalled product, controlled substances, and hazardous production waste.",
    bullets: ["Bulk expired, off-spec & recalled product", "Registrant-to-registrant controlled destruction (Form 41)", "Hazardous production & QC waste", "Witnessed destruction, manifests & chain of custody"],
    audience: "QA/RA, supply chain, and EH&S leaders at manufacturers and distributors.",
    industry: "Manufacturer / Distributor",
    cover: "/images/guides/pharma-manufacturers.jpg",
  },
  {
    slug: "ems-fire-waste-disposal-guide",
    file: "/downloads/guides/ems-fire.pdf",
    eyebrow: "Free guide · for EMS & fire departments",
    h1: "The EMS / Fire Department's Guide to Compliant Waste Disposal",
    keyword: "EMS controlled substance disposal guide",
    title: "EMS & Fire Department Waste Disposal Guide (Free Download)",
    desc: "Free EMS & fire waste disposal guide — rig narcotics (fentanyl, morphine, midazolam) destroyed non-retrievable with witnessed field-wasting logs and Form 41, plus field sharps and ambulance biohazard.",
    intro: "A plain-English reference to every regulated waste stream an EMS agency or fire department generates — rig narcotics, field sharps, and ambulance biohazard — with the DEA documentation field wasting demands.",
    bullets: ["Rig narcotics: field wasting, logs & Form 41", "How to pass DEA scrutiny of EMS wasting", "Field & ambulance sharps", "Trauma biohazard — handled & documented"],
    audience: "EMS chiefs, fire department medical officers, and controlled-substance coordinators.",
    industry: "EMS / Fire",
    cover: "/images/guides/ems-fire.jpg",
  },
  {
    slug: "funeral-home-waste-disposal-guide",
    file: "/downloads/guides/funeral-homes.pdf",
    eyebrow: "Free guide · for funeral homes & mortuaries",
    h1: "The Funeral Home's Guide to Compliant Waste Disposal",
    keyword: "funeral home waste disposal guide",
    title: "Funeral Home Waste Disposal Guide (Free Download)",
    desc: "Free funeral home waste disposal guide — hazardous embalming chemicals (formaldehyde), trocar and preparation sharps, blood/OPIM biohazard, and a deceased's leftover medications: every stream, handled right.",
    intro: "A plain-English reference to every regulated waste stream a funeral home or mortuary generates — embalming chemicals, preparation sharps, biohazard, and unwanted medications — and how to handle each.",
    bullets: ["Embalming chemicals & formaldehyde — hazardous waste", "Trocars & preparation sharps", "Blood/OPIM biohazard", "A deceased's leftover medications"],
    audience: "Funeral directors, embalmers, and mortuary managers.",
    industry: "Funeral Home",
    cover: "/images/guides/funeral-homes.jpg",
  },
  {
    slug: "crime-scene-cleanup-waste-disposal-guide",
    file: "/downloads/guides/crime-scene.pdf",
    eyebrow: "Free guide · for trauma & crime-scene remediation",
    h1: "The Trauma / Crime-Scene Cleanup Guide to Compliant Waste Disposal",
    keyword: "crime scene cleanup waste disposal guide",
    title: "Trauma & Crime-Scene Cleanup Waste Disposal Guide (Free Download)",
    desc: "Free trauma & crime-scene cleanup waste disposal guide — bulk biohazard on your timeline, plus found sharps and found drugs (including controlled substances) that need documented, non-retrievable destruction.",
    intro: "A plain-English reference to every regulated waste stream a trauma or crime-scene remediation company generates — bulk biohazard, found sharps, and found medications — with the documentation your clients expect.",
    bullets: ["Bulk biohazard on your timeline", "Found sharps recovered from scenes", "Found controlled substances: chain of custody + Form 41", "A remediation checklist, cheat sheet & FAQ"],
    audience: "Owners and crews at trauma, biohazard, and crime-scene remediation companies.",
    industry: "Trauma / Crime-Scene",
    cover: "/images/guides/crime-scene.jpg",
  },
  {
    slug: "animal-shelter-waste-disposal-guide",
    file: "/downloads/guides/animal-shelters.pdf",
    eyebrow: "Free guide · for animal shelters & control",
    h1: "The Animal Shelter's Guide to Compliant Waste Disposal",
    keyword: "animal shelter controlled substance disposal guide",
    title: "Animal Shelter Waste Disposal Guide (Free Download)",
    desc: "Free animal shelter waste disposal guide — euthanasia controls (pentobarbital) the DEA regulates like human controls, destroyed non-retrievable with Form 41, plus sharps, expired meds, and biohazard.",
    intro: "A plain-English reference to every regulated waste stream an animal shelter or control facility generates — euthanasia controls, sharps, expired meds, and biohazard — and how to handle each.",
    bullets: ["Euthanasia solution (pentobarbital): Form 41 + logs", "Euthanasia & injection sharps", "Expired animal medications", "An animal-shelter checklist, cheat sheet & FAQ"],
    audience: "Shelter directors, veterinary staff, and municipal animal control.",
    industry: "Animal Shelter",
    cover: "/images/guides/animal-shelters.jpg",
  },
  {
    slug: "independent-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/independent-pharmacy.pdf",
    eyebrow: "Free guide · for independent pharmacies",
    h1: "The Independent Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "independent pharmacy waste disposal guide",
    title: "Independent Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free independent pharmacy waste disposal guide — expired and returned stock, controlled returns (Form 41), RCRA-hazardous drugs like warfarin and nicotine, immunization sharps, and patient take-back.",
    intro: "A plain-English reference to every regulated waste stream an independent pharmacy generates — controlled returns, hazardous drugs, expired stock, and immunization sharps — and how to sort and destroy each.",
    bullets: ["Expired & returned controlled stock (Form 41)", "RCRA-hazardous drugs (warfarin, nicotine)", "Expired non-controlled stock", "Immunization sharps & patient take-back"],
    audience: "Independent pharmacy owners, PICs, and staff.",
    industry: "Independent Pharmacy",
    cover: "/images/guides/independent-pharmacy.jpg",
  },
  {
    slug: "chain-pharmacy-waste-disposal-guide",
    file: "/downloads/guides/chain-pharmacy.pdf",
    eyebrow: "Free guide · for chain & retail pharmacies",
    h1: "The Chain / Retail Pharmacy's Guide to Compliant Waste Disposal",
    keyword: "chain pharmacy waste disposal guide",
    title: "Chain & Retail Pharmacy Waste Disposal Guide (Free Download)",
    desc: "Free chain & retail pharmacy waste disposal guide — controlled returns, RCRA-hazardous drugs, expired stock, and take-back kiosks standardized and documented across every store, at scale.",
    intro: "A plain-English reference to every regulated waste stream a chain or retail pharmacy generates — controlled returns, hazardous drugs, expired stock, and take-back kiosks — standardized across locations.",
    bullets: ["Controlled destruction at scale (Form 41)", "One hazardous-drug standard, chain-wide", "Take-back kiosk servicing (DEA collector rules)", "Unified documentation across every store"],
    audience: "Pharmacy operations, compliance, and EH&S leaders at chains and retail pharmacy groups.",
    industry: "Chain / Retail Pharmacy",
    cover: "/images/guides/chain-pharmacy.jpg",
  },
  {
    slug: "cannabis-waste-disposal-guide",
    file: "/downloads/guides/cannabis.pdf",
    eyebrow: "Free guide · for cannabis operators",
    h1: "The Cannabis Operator's Guide to Compliant Waste Disposal",
    keyword: "cannabis waste disposal guide",
    title: "Cannabis Operator Waste Disposal Guide (Free Download)",
    desc: "Free cannabis waste disposal guide — state-mandated product destruction (rendered unusable, witnessed, track-and-trace), hazardous extraction chemicals, and vape hardware / battery waste, documented for your regulator.",
    intro: "A plain-English reference to every regulated waste stream a licensed cannabis operator generates — state-mandated product destruction, extraction chemicals, and vape hardware — and how we support your compliance.",
    bullets: ["State-mandated product destruction & track-and-trace", "Extraction solvents & processing chemicals", "Vape hardware & battery (universal) waste", "A cannabis-operator checklist, cheat sheet & FAQ"],
    audience: "Compliance and operations leaders at cannabis cultivators, processors, and dispensaries.",
    industry: "Cannabis",
    cover: "/images/guides/cannabis.jpg",
  },
  {
    slug: "sharps-disposal-compliance-guide",
    file: "/downloads/guides/sol-sharps-disposal.pdf",
    eyebrow: "Free guide · sharps disposal",
    h1: "The Sharps Disposal Compliance Guide",
    keyword: "sharps disposal compliance",
    title: "Sharps Disposal Compliance Guide (Free PDF Download)",
    desc: "Free guide to OSHA- and DOT-compliant sharps disposal — what counts as a sharp, container sizing, the rules, and how mail-back destruction closes the loop with a Certificate of Destruction.",
    intro: "Everything you need to handle needles, syringes, pens, and lancets the compliant way — the OSHA and DOT rules, how to size and fill a container, and the simplest path to destruction.",
    bullets: [
      "What counts as a regulated sharp — and what doesn't",
      "The OSHA Bloodborne Pathogens container and labeling rules",
      "How to size and fill a container so you stay compliant",
      "A ready-to-use sharps compliance checklist",
      "FAQ: insulin pens, chemo sharps, cost, and mail-back",
    ],
    audience: "Clinics, offices, and home users disposing of needles and other sharps.",
    cover: "/images/guides/sharps-disposal-compliance-guide.jpg",
  },
  {
    slug: "controlled-substance-destruction-guide",
    file: "/downloads/guides/sol-controlled-substance-destruction.pdf",
    eyebrow: "Free guide · for DEA registrants",
    h1: "The Controlled Substance Destruction Guide",
    keyword: "controlled substance destruction",
    title: "Controlled Substance Destruction Guide (Free PDF Download)",
    desc: "Free guide to DEA-compliant controlled substance destruction — the non-retrievable standard, DEA Form 41 and 222, witnessed waste, and how a registrant destroys controls the right way.",
    intro: "A clear walkthrough of the DEA non-retrievable standard, on-site waste vs. inventory destruction, when a Form 41 or 222 is required, and how to keep every event audit-ready.",
    bullets: [
      "What 'non-retrievable' actually means under 21 CFR 1317",
      "When you need a DEA Form 41 vs. a Form 222",
      "Witnessed waste and recordkeeping that survives an audit",
      "A controlled-substance destruction checklist",
      "FAQ: flushing, on-site waste, inventory, and record retention",
    ],
    audience: "DEA registrants — prescribers, pharmacies, hospitals, and clinics.",
    cover: "/images/guides/controlled-substance-destruction-guide.jpg",
  },
  {
    slug: "pharmaceutical-waste-disposal-guide",
    file: "/downloads/guides/sol-pharmaceutical-waste-disposal.pdf",
    eyebrow: "Free guide · pharmaceutical waste",
    h1: "The Pharmaceutical Waste Disposal Guide",
    keyword: "pharmaceutical waste disposal",
    title: "Pharmaceutical Waste Disposal Guide (Free PDF Download)",
    desc: "Free guide to pharmaceutical waste disposal — how to segregate non-hazardous, RCRA-hazardous, and controlled drug waste, why the drain is off-limits, and how to destroy each stream compliantly.",
    intro: "Pharmaceutical waste is really three streams wearing one name. This guide shows how to segregate each at the point of generation and destroy it by the right method.",
    bullets: [
      "Non-hazardous vs. RCRA-hazardous vs. controlled drug waste",
      "A point-of-generation decision rule your staff can apply in seconds",
      "Why hazardous waste pharmaceuticals can never be sewered",
      "A by-stream pharmaceutical waste checklist",
      "FAQ: drain disposal, dual-classified drugs, and one-vendor handling",
    ],
    audience: "Pharmacies, hospitals, and clinics managing drug waste.",
    cover: "/images/guides/pharmaceutical-waste-disposal-guide.jpg",
  },
  {
    slug: "biohazard-rmw-disposal-guide",
    file: "/downloads/guides/sol-biohazard-waste-disposal.pdf",
    eyebrow: "Free guide · biohazard / RMW",
    h1: "The Biohazard & RMW Disposal Guide",
    keyword: "biohazard waste disposal",
    title: "Biohazard & Regulated Medical Waste Disposal Guide (Free PDF)",
    desc: "Free guide to biohazard and regulated medical waste — what actually qualifies as red-bag RMW, how to package and label it, the state rules that vary, and how it's treated and destroyed.",
    intro: "Most of what ends up in a red bag doesn't belong there. This guide tightens your definition of RMW, gets the packaging right, and explains the state rules that decide the rest.",
    bullets: [
      "What qualifies as regulated medical waste — and what doesn't",
      "Red-bag packaging and labeling that stays compliant in transit",
      "Why RMW rules vary so much by state",
      "A biohazard / RMW compliance checklist",
      "FAQ: sharps in red bags, mail-back limits, and treatment methods",
    ],
    audience: "Facilities generating blood- and fluid-contaminated waste.",
    cover: "/images/guides/biohazard-rmw-disposal-guide.jpg",
  },
  {
    slug: "rcra-hazardous-drug-waste-guide",
    file: "/downloads/guides/sol-rcra-hazardous-pharmaceutical-waste.pdf",
    eyebrow: "Free guide · RCRA hazardous drugs",
    h1: "The RCRA Hazardous Drug Waste Guide",
    keyword: "RCRA hazardous pharmaceutical waste",
    title: "RCRA Hazardous Drug Waste Guide (Free PDF Download)",
    desc: "Free guide to RCRA hazardous pharmaceutical waste — the P-list, U-list, and characteristic wastes, what Subpart P changed, the sewer ban, and how to identify and destroy hazardous drug waste.",
    intro: "A subset of the drugs on your shelf are federally hazardous waste the moment you discard them. This guide explains how to identify them and destroy them under RCRA Subpart P.",
    bullets: [
      "P-listed, U-listed, and characteristic (D-code) drug waste",
      "What Subpart P changed for healthcare facilities",
      "The absolute ban on sewering hazardous waste pharmaceuticals",
      "Why nicotine and warfarin are hazardous waste",
      "A RCRA hazardous drug waste checklist + FAQ",
    ],
    audience: "Hospitals, pharmacies, and facilities with hazardous drug waste.",
    cover: "/images/guides/rcra-hazardous-drug-waste-guide.jpg",
  },
  {
    slug: "reverse-distribution-guide",
    file: "/downloads/guides/sol-reverse-distribution.pdf",
    eyebrow: "Free guide · reverse distribution",
    h1: "The Reverse Distribution Guide",
    keyword: "pharmaceutical reverse distribution",
    title: "Reverse Distribution Guide (Free PDF Download)",
    desc: "Free guide to pharmaceutical reverse distribution — creditable returns vs. destruction, what qualifies for credit, DSCSA chain-of-custody, and how controlled and hazardous returns are handled.",
    intro: "Much of what you'd otherwise pay to destroy may be returnable for credit. This guide shows how to sort creditable from non-creditable stock and handle each compliantly.",
    bullets: [
      "What qualifies for manufacturer credit vs. destruction",
      "DSCSA chain-of-custody for returned pharmaceuticals",
      "How controlled returns use a DEA-registered reverse distributor",
      "Routing non-creditable hazardous drugs to RCRA destruction",
      "A reverse distribution checklist + FAQ",
    ],
    audience: "Pharmacies, wholesalers, and manufacturers processing returns.",
    cover: "/images/guides/reverse-distribution-guide.jpg",
  },
  {
    slug: "medication-mail-back-kit-guide",
    file: "/downloads/guides/sol-medication-disposal-kit.pdf",
    eyebrow: "Free guide · medication mail-back",
    h1: "The Medication Mail-Back Kit Guide",
    keyword: "medication mail-back kit",
    title: "Medication Mail-Back Kit Guide (Free PDF Download)",
    desc: "Free guide to DEA-authorized medication mail-back kits — what they can and can't collect, who is authorized to offer them, how controlled substances are handled, and the documentation you get back.",
    intro: "A mail-back kit is the simplest DEA-authorized way to collect and destroy unused medication — including controlled substances. This guide explains exactly how they work.",
    bullets: [
      "What a DEA mail-back package can and can't collect",
      "Who can be an authorized collector — pharmacies, LTC, clinics",
      "How controlled and non-controlled meds go in one sealed liner",
      "Documentation and non-retrievable destruction explained",
      "A medication mail-back checklist + FAQ",
    ],
    audience: "Pharmacies, LTC facilities, clinics, and households.",
    cover: "/images/guides/medication-mail-back-kit-guide.jpg",
  },
  {
    slug: "trace-chemotherapy-waste-guide",
    file: "/downloads/guides/sol-trace-chemotherapy-waste.pdf",
    eyebrow: "Free guide · trace chemo waste",
    h1: "The Trace Chemo Waste Guide",
    keyword: "trace chemotherapy waste disposal",
    title: "Trace Chemotherapy Waste Guide (Free PDF Download)",
    desc: "Free guide to trace chemotherapy waste — trace vs. bulk, the RCRA-empty rule, the yellow-container system, and how USP 800 shapes safe handling and disposal of chemo waste.",
    intro: "Chemo waste splits into two very different streams. This guide draws the one line between trace and bulk, explains the RCRA-empty rule, and shows how USP 800 shapes handling.",
    bullets: [
      "Trace vs. bulk chemo — and why it matters",
      "The RCRA-empty definition that separates the two",
      "What goes in the yellow container (and what doesn't)",
      "How USP 800 governs hazardous-drug handling through disposal",
      "A trace chemo checklist + FAQ",
    ],
    audience: "Oncology, infusion, and hazardous-drug handling teams.",
    cover: "/images/guides/trace-chemotherapy-waste-guide.jpg",
  },
  {
    slug: "sample-certificate-of-destruction",
    file: "/downloads/sample-certificate-of-destruction.pdf",
    eyebrow: "Free download · sample document",
    h1: "Sample Certificate of Destruction",
    keyword: "sample certificate of destruction",
    title: "Sample Certificate of Destruction (Free PDF)",
    desc: "See exactly what you receive after every order — a specimen Certificate of Destruction showing the fields, method, and compliance attestation Easy Rx Cycle issues.",
    intro: "A specimen of the Certificate of Destruction issued with every order — so you know exactly what documentation lands in your records.",
    bullets: [
      "Every field on the certificate you receive",
      "The non-retrievable destruction attestation (DEA 21 CFR 1317)",
      "Method of destruction and permitted facility line",
      "What auditors look for on a valid COD",
    ],
    audience: "Compliance officers and procurement vetting a disposal vendor.",
    cover: "/images/guides/sample-certificate-of-destruction.jpg",
  },
  {
    slug: "line-card",
    file: "/downloads/line-card.pdf",
    eyebrow: "Free download · for procurement & partners",
    h1: "Easy Rx Cycle Line Card",
    keyword: "medical waste line card",
    title: "Easy Rx Cycle Line Card / Sell Sheet (Free PDF)",
    desc: "A one-page line card of every Easy Rx Cycle service — sharps, controlled substance destruction, pharmaceutical, RCRA-hazardous, biohazard, reverse distribution, mail-back kits, and trace chemo — with credentials and contacts.",
    intro: "A one-page overview of every regulated waste stream we handle, our credentials, and how to get started — built for procurement teams, distributors, and partners.",
    bullets: [
      "All eight service lines on one page",
      "Credentials: DEA, EPA/RCRA, DOT, HIPAA/BAA",
      "How the mail-back and pickup process works",
      "Direct contacts for a quote or line-card pricing",
    ],
    audience: "Procurement, distributors, brokers, and GPO partners.",
    cover: "/images/guides/line-card.jpg",
  },
];

export const MAGNET_BY_SLUG: Record<string, LeadMagnet> = Object.fromEntries(MAGNETS.map((m) => [m.slug, m]));
